### ISSUE TITLE
explorer can't be installed with done from node robot

### ISSUE THREAD

**Issue by zaibon** [threefoldtoken/0-templates#18]
My tests uses: [zero-os-v1.2.1-0-core-51c5025bf0.efi](https://bootstrap.gig.tech/kernel/zero-os-v1.2.1.efi)
as kernel for 0-OS.

Then I installed an explore service like:
```python
data = {'node':'local','domain':'zaibon.be','network':'testnet'}
exp = r.services.create('github.com/threefoldtoken/0-templates/explorer/0.0.1','explorer',data)
t = exp.schedule_action('install')
```
and I get this error in the eco of the task:
```
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/threefoldtoken/0-templates/templates/explorer/explorer.py", line 85, in install
    self._explorer_sal.start()
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9Lib/clients/zero_os/sal/TfChain.py", line 100, in start
    self._start_caddy(timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9Lib/clients/zero_os/sal/TfChain.py", line 139, in _start_caddy
    config = templates.render('tf_explorer_caddy.conf', domain=self.domain)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9Lib/clients/zero_os/sal/templates/__init__.py", line 13, in render
    env = get(templatename)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9Lib/clients/zero_os/sal/templates/__init__.py", line 9, in get
    return env.get_template(templatename)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: tf_explorer_caddy.conf
```

**Comment by zaibon** [comment]
was a problem in the way we build the flist, it has been solved in : https://github.com/zero-os/0-robot/commit/70b6a999e4847aa17057f81a07f561a31ab4074f
