### ISSUE TITLE
explorer upgrade action fails

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtoken/0-templates#25]
```
In [6]: task = explorer.schedule_action('upgrade')

In [7]: task.wait()

In [8]: task.state
Out[8]: 'error'

In [9]: task.eco
Out[9]: Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 57, in get
    raise StateCategoryNotExistsError("category %s does not exist" % category)
zerorobot.template.state.StateCategoryNotExistsError: category actions does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/zero-os/0-templates/templates/container/container.py", line 73, in start
    self.state.check('actions', 'install', 'ok')
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:install:ok failed
check for state actions:install:ok failed
```

**Comment by zaibon** [comment]
That's just a state error which says that the service is not installed.
You can't upgrade something that is not installed yet

**Comment by LeeSmet** [comment]
The service was installed though. The explorer was running, then I did the actions linked above. I assume that the explorer can't run before it is installed

**Comment by LeeSmet** [comment]
This is the entire ipython sessions:

```
* ***Application started***: jsshell
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: robot = j.clients.zrobot.robots['bootstrap-4']
[Thu03 12:09] - Config.py         :61  :j.config             - DEBUG    - init getpath:None
[Thu03 12:09] - Config.py         :64  :j.config             - DEBUG    - getpath:/opt/cfg/myconfig/j.clients.zrobot/bootstrap-4.toml
[Thu03 12:09] - Config.py         :61  :j.config             - DEBUG    - init getpath:/opt/cfg/myconfig/j.clients.zrobot/bootstrap-4.toml
[Thu03 12:09] - Config.py         :61  :j.config             - DEBUG    - init getpath:/opt/cfg/myconfig/j.clients.zrobot/bootstrap-4.toml
[Thu03 12:09] - Config.py         :61  :j.config             - DEBUG    - init getpath:None
[Thu03 12:09] - Config.py         :64  :j.config             - DEBUG    - getpath:/opt/cfg/myconfig/j.clients.zrobot/bootstrap-5.toml
[Thu03 12:09] - Config.py         :61  :j.config             - DEBUG    - init getpath:/opt/cfg/myconfig/j.clients.zrobot/bootstrap-5.toml
[Thu03 12:09] - Config.py         :61  :j.config             - DEBUG    - init getpath:/opt/cfg/myconfig/j.clients.zrobot/bootstrap-5.toml

In [2]: robot.services.uids

AttributeErrorTraceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 robot.services.uids

AttributeError: 'ServicesMgr' object has no attribute 'uids'

In [3]: robot.services.find()
Out[3]: 
[robot://bootstrap-4/github.com/threefoldtoken/0-templates/explorer/0.0.1?guid=1efcabdd-afe6-49df-8942-743470c5d125&name=explorer,
 robot://bootstrap-4/github.com/zero-os/0-templates/container/0.0.1?guid=3575f09d-e458-4bcb-a41f-e29cfef7ff63&name=container-8ceb91c2-433c-4ad1-92c6-27cb37715a3f,
 robot://bootstrap-4/github.com/threefoldtoken/0-templates/explorer/0.0.1?guid=4f532e0b-eecb-4ba1-8213-77cec67feb1a&name=testnet-explorer,
 robot://bootstrap-4/github.com/zero-os/0-templates/container/0.0.1?guid=63773163-3747-49e4-ae84-f9275333161e&name=container-4f532e0b-eecb-4ba1-8213-77cec67feb1a,
 robot://bootstrap-4/github.com/zero-os/0-templates/container/0.0.1?guid=c45454ac-2453-4035-b17a-97b116fb8c5c&name=container-1efcabdd-afe6-49df-8942-743470c5d125]

In [4]: explorer = _[2]

In [5]: explorer.actions
Out[5]: 
['consensus_stat',
 'delete',
 'gateway_stat',
 'install',
 'start',
 'stop',
 'uninstall',
 'update_data',
 'upgrade']

In [6]: task = explorer.schedule_action('upgrade')

In [7]: task.wait()

In [8]: task.state
Out[8]: 'error'

In [9]: task.eco
Out[9]: Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 57, in get
    raise StateCategoryNotExistsError("category %s does not exist" % category)
zerorobot.template.state.StateCategoryNotExistsError: category actions does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/zero-os/0-templates/templates/container/container.py", line 73, in start
    self.state.check('actions', 'install', 'ok')
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:install:ok failed
check for state actions:install:ok failed

In [10]: explorer.state
Out[10]: {'actions': {'install': 'ok'}}

In [11]: task = explorer.schedule_action('install')

In [12]: task.wait()

In [13]: task.state
Out[13]: 'ok'

In [14]: task = explorer.schedule_action('start')

In [15]: task.wait()

In [16]: task.state
Out[16]: 'ok'

In [17]: explorer.state
Out[17]: {'status': {'running': 'ok'}, 'actions': {'start': 'ok', 'install': 'ok'}}
```
